(define (square x) (* x x))
(define (compose f g)
  (lambda (x) (f (g x))))
(define (repeated f n)
  (define (loop i result)
    (if (= i n)
        result
        (loop (+ i 1) (compose f result))))
  (loop 1 f))

(display "Expect: 25, Result = ")
((repeated square 1) 5) ;(5^2)
(newline)
(display "Expect: 625, Result = ")
((repeated square 2) 5) ;(5^4)
(newline)
(display "Expect: 4096, Result = ")
((repeated square 2) 8) ;(8^4)
(newline)
(display "Expect: 4294967296, Result = ")
((repeated square 5) 2) ;(2^32)